### ISSUE TITLE
Intelli idea community trouble

### ISSUE THREAD

**Issue by skvarovski** [Android-Academy-Global/2020-Fundamentals-Kotlin#21]
Добрый день, сделал по инструкции
но ошибка 

Build file 'C:\Android\2020-Fundamentals-Kotlin1\build.gradle' line: 2

Plugin [id: 'org.jetbrains.kotlin.jvm', version: '1.3.72'] was not found in any of the following sources:

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

windows 10 64bit

**Comment by webanimal** [comment]
Не самый срочный способ связи.
Проблема с подключением плагина, либо с синхронизацией gradle проекта, либо с интернет в момент запуска проекта, либо ещё что-то подобное.

Посмотри [здесь по твоему багу](https://stackoverflow.com/questions/52562735/plugin-id-org-jetbrains-kotlin-jvm-version-1-2-71-was-not-found-in-any)

Посмотри [как можно установить плагин Kotlin под Gradle](https://kotlinlang.ru/docs/reference/compiler-plugins.html)

Следующая лекция 02.11.2020: "Default project setup and explanation".
Работа будет вестись в уже Android Studio, первое занятие как раз посвящается настройкам проекта с нуля.

Занятие по Котлин было в InteliJ Idea, т.к. надо было работать только с чистым языком, быстро запускать функции main, и не тащить за собой среду Android.

По всем срочным вопросам обращайся в чат академии, либо сразу к @ определённому_ментору, либо просто: "Менторы нужна помощь в том-то", или "Организаторы ..."
